name: CD

on:
  push:
    branches: ["master", "main"]
    paths-ignore: [ "docs/**" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: AWS SSM Send Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
          aws-region: ${{ secrets.AWS_REGION }}
          instance-ids: ${{ secrets.INSTANCE_ID  }}

          comment: Deploy branch
          working-directory: /home/waffle/app/special-waffle
          command: /bin/sh ./deploy.sh
      - name: Get the outputs
        run: echo "The Command id is ${{ steps.ssm.outputs }}"
